global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'zato-apps'
    metrics_path: '/metrics'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:17010', 'localhost:17011']
    scrape_timeout: 10s

  - job_name: 'zato-server'
    metrics_path: '/metrics'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:17012']
    scrape_timeout: 10s

  - job_name: 'test-server'
    metrics_path: '/metrics'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:8080']
