[tool.pyright]
pythonVersion = "3.8"
typeCheckingMode = "basic"

#
# This is level 1
#
#reportOptionalOperand       = "none"
#reportGeneralTypeIssues     = "none"
#reportOptionalMemberAccess  = "none"
reportPrivateUsage        = "none"
reportAssertAlwaysTrue    = "error"
reportUnusedImport        = "error"
reportUnusedFunction      = "error"
reportUnusedCallResult    = "error"
reportUnusedVariable      = "none"
reportInvalidTypeVarUse   = "error"
reportOverlappingOverload = "error"
reportPropertyTypeMismatch  = "error"
reportUntypedClassDecorator = "error"
reportUnnecessaryCast       = "error"
reportUnnecessaryComparison = "error"
reportUnnecessaryIsInstance = "error"
reportUnsupportedDunderAll  = "error"
reportUntypedFunctionDecorator    = "error"
reportWildcardImportFromLibrary   = "error"
reportImplicitStringConcatenation = "error"
reportSelfClsParameterName = "none"

reportUnknownLambdaType    = "none"
reportUnknownMemberType    = "none"
reportUnknownParameterType = "none"
reportUnknownVariableType  = "none"
reportTypeCommentUsage     = "none"

#
# This is level 2
#
reportMissingImports        = "none"
reportGeneralTypeIssues     = "none"
reportOptionalMemberAccess  = "none"
reportMissingModuleSource   = "error"

#
# This is level 3
#
reportMissingParameterType = "none"

#
# This is level 4, needed before reportUnknownMemberType
#
#reportUnknownArgumentType  = "error"

#
# This is level 5
#
#reportUnknownLambdaType    = "error"
#reportUnknownMemberType    = "error"
#reportUnknownParameterType = "error"
#reportUnknownVariableType  = "error"
#reportUntypedClassDecorator    = "error"
#reportUntypedFunctionDecorator = "error"

extraPaths = [
    "./lib/python3.8/site-packages",
    "./zato-agent/src",
    "./zato-cli/src",
    "./zato-common/src",
    "./zato-cy/src",
    "./zato-distlock/src",
    "./zato-hl7/src",
    "./zato-scheduler/src",
    "./zato-server/src",
    "./zato-sso/src",
    "./zato-testing/src",
    "./zato-web-admin/src",
    "./zato-zmq/src",
]
