[tool.pyright]
pythonVersion = "3.8"
typeCheckingMode = "basic"

#
# This is level 1
#
reportGeneralTypeIssues     = "none"
reportOptionalMemberAccess  = "none"
reportPrivateUsage        = "error"
reportAssertAlwaysTrue    = "error"
reportUnusedImport        = "error"
reportUnusedFunction      = "error"
reportUnusedCallResult    = "error"
reportUnusedVariable      = "error"
reportInvalidTypeVarUse   = "error"
reportOverlappingOverload = "error"
reportPropertyTypeMismatch  = "error"
reportUntypedClassDecorator = "error"
reportUnnecessaryCast       = "error"
reportUnnecessaryComparison = "error"
reportUnnecessaryIsInstance = "error"
reportUnsupportedDunderAll  = "error"
reportUntypedFunctionDecorator    = "error"
reportWildcardImportFromLibrary   = "error"
reportImplicitStringConcatenation = "error"

#
# This is level 2
#
#reportGeneralTypeIssues    = "error"
#reportOptionalMemberAccess = "error"

#
# This is level 3
#
#reportMissingParameterType = "error"

#
# This is level 4, needed before reportUnknownMemberType
#
#reportUnknownArgumentType  = "error"

#
# This is level 5
#
#reportUnknownLambdaType    = "error"
#reportUnknownMemberType    = "error"
#reportUnknownParameterType = "error"
#reportUnknownVariableType  = "error"

extraPaths = [
    "./lib/python3.8/site-packages",
    "./zato-agent/src",
    "./zato-cli/src",
    "./zato-common/src",
    "./zato-cy/src",
    "./zato-distlock/src",
    "./zato-hl7/src",
    "./zato-scheduler/src",
    "./zato-server/src",
    "./zato-sso/src",
    "./zato-testing/src",
    "./zato-web-admin/src",
    "./zato-zmq/src",
]
